appname: "cl.gs"
# use nginx to proxy-forward from port 80
port: 3004
layout  : "main"
charset : "UTF-8"
template: "template_toolkit"
engines :
  template_toolkit:
    encoding : 'utf8'
    start_tag: '[%'
    end_tag  : '%]'

cl.gs:
   cookie_name: "__clgs"
   #cookie_expires: Thu, 01-Jan-1971 01:00:00 GMT
   cookie_expires: 3600

plugins:
    Redis:
        server: '127.0.0.1:6379'
        debug: 0
        encoding: utf8
        #connection_check_threshold: 30
        connections:
            test:
                server: '127.0.0.1:6380'
                debug: 1
                encoding: utf8
