# configuration file for production environment

# log message to a file in logs/
logger: "file"

# only log warning and error messsages
log: "warning"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1
